import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "Lavender Dreams",
    description:
      "Handcrafted soy wax candle with calming lavender essential oils. Perfect for relaxation and unwinding after a long day.",
    price: 1200,
    image: "/lavender-scented-candle-in-glass-jar.jpg",
    images: [
      "/lavender-scented-candle-in-glass-jar.jpg",
      "/lavender-candle-detail-1.jpg",
      "/lavender-candle-detail-2.jpg",
      "/lavender-candle-detail-3.jpg",
    ],
    scent: "Lavender",
    scentDescription:
      "A soothing blend of French lavender with subtle hints of chamomile and vanilla. This calming fragrance creates a peaceful atmosphere perfect for meditation, yoga, or winding down before bedtime.",
    size: "Medium (200g)",
    stock: 15,
    rating: 4.8,
    burnTime: 45,
    careInstructions: [
      "Trim wick to 1/4 inch before each use",
      "Burn for 2-3 hours at a time for optimal performance",
      "Keep away from drafts and flammable materials",
      "Never leave a burning candle unattended",
      "Stop use when 1/2 inch of wax remains",
    ],
    ingredients: [
      "100% Natural Soy Wax",
      "Pure Lavender Essential Oil",
      "Chamomile Extract",
      "Cotton Wick",
      "Natural Violet Colorant",
    ],
    relatedProducts: ["2", "8", "7"],
    reviews: [
      {
        id: "r1",
        author: "Sarah M.",
        rating: 5,
        comment: "Amazing scent! Burns evenly and lasts so long.",
        date: "2024-01-15",
      },
      {
        id: "r2",
        author: "John K.",
        rating: 4,
        comment: "Great quality, smells wonderful.",
        date: "2024-01-10",
      },
    ],
  },
  {
    id: "2",
    name: "Vanilla Bliss",
    description: "Warm and comforting vanilla scent made with natural soy wax. Creates a cozy atmosphere in any room.",
    price: 1200,
    image: "/vanilla-scented-candle-in-cream-jar.jpg",
    images: [
      "/vanilla-scented-candle-in-cream-jar.jpg",
      "/vanilla-candle-detail-1.jpg",
    ],
    scent: "Vanilla",
    scentDescription:
      "Rich Madagascar vanilla bean combined with warm caramel and a touch of sweet cream. This comforting fragrance fills your space with warmth and creates an inviting atmosphere.",
    size: "Medium (200g)",
    stock: 12,
    rating: 4.9,
    burnTime: 42,
    careInstructions: [
      "Trim wick to 1/4 inch before each use",
      "Burn for 2-3 hours at a time for optimal performance",
      "Keep away from drafts and flammable materials",
      "Never leave a burning candle unattended",
      "Stop use when 1/2 inch of wax remains",
    ],
    ingredients: [
      "100% Natural Soy Wax",
      "Pure Vanilla Extract",
      "Caramel Essence",
      "Cotton Wick",
      "Natural Cream Colorant",
    ],
    relatedProducts: ["1", "6", "3"],
    bundleOffer: {
      quantity: 3,
      discount: 10,
      description: "Buy 3 Get 10% Off",
    },
    reviews: [
      {
        id: "r3",
        author: "Emma L.",
        rating: 5,
        comment: "Love the vanilla scent, not too overpowering!",
        date: "2024-01-18",
      },
    ],
  },
  {
    id: "3",
    name: "Citrus Burst",
    description:
      "Energizing blend of orange, lemon, and grapefruit oils. Perfect for morning routines and boosting your mood.",
    price: 1200,
    image: "/citrus-scented-candle-yellow-jar.jpg",
    scent: "Citrus",
    size: "Medium (200g)",
    stock: 20,
    rating: 4.7,
    reviews: [],
  },
  {
    id: "4",
    name: "Ocean Breeze",
    description: "Fresh and clean scent reminiscent of coastal air. Made with natural sea salt and marine notes.",
    price: 1500,
    image: "/ocean-breeze-scented-candle-blue-jar.jpg",
    scent: "Fresh",
    size: "Large (300g)",
    stock: 8,
    rating: 4.6,
    reviews: [
      {
        id: "r4",
        author: "Michael T.",
        rating: 5,
        comment: "Smells like the beach! So refreshing.",
        date: "2024-01-12",
      },
    ],
  },
  {
    id: "5",
    name: "Rose Garden",
    description: "Elegant rose petals combined with subtle hints of jasmine. Perfect for romantic evenings.",
    price: 1500,
    image: "/rose-scented-candle-pink-jar.jpg",
    scent: "Floral",
    size: "Large (300g)",
    stock: 10,
    rating: 4.9,
    reviews: [],
  },
  {
    id: "6",
    name: "Cinnamon Spice",
    description: "Warm cinnamon with notes of clove and nutmeg. Creates a cozy, festive atmosphere.",
    price: 900,
    image: "/cinnamon-scented-candle-brown-jar.jpg",
    scent: "Spice",
    size: "Small (100g)",
    stock: 25,
    rating: 4.8,
    reviews: [
      {
        id: "r5",
        author: "Lisa P.",
        rating: 5,
        comment: "Perfect for the holidays!",
        date: "2024-01-20",
      },
    ],
  },
  {
    id: "7",
    name: "Eucalyptus Mint",
    description: "Refreshing eucalyptus paired with cool peppermint. Great for focus and clarity.",
    price: 900,
    image: "/eucalyptus-mint-scented-candle-green-jar.jpg",
    scent: "Fresh",
    size: "Small (100g)",
    stock: 18,
    rating: 4.7,
    reviews: [],
  },
  {
    id: "8",
    name: "Sandalwood Serenity",
    description: "Rich sandalwood with earthy undertones. Perfect for meditation and relaxation.",
    price: 1500,
    image: "/sandalwood-scented-candle-wooden-jar.jpg",
    scent: "Woody",
    size: "Large (300g)",
    stock: 7,
    rating: 4.9,
    reviews: [
      {
        id: "r6",
        author: "David R.",
        rating: 5,
        comment: "Best candle I have ever purchased!",
        date: "2024-01-22",
      },
    ],
  },
]

export const scents = ["All", "Lavender", "Vanilla", "Citrus", "Fresh", "Floral", "Spice", "Woody"]
export const sizes = ["All", "Small (100g)", "Medium (200g)", "Large (300g)"]
export const priceRanges = [
  { label: "All", min: 0, max: Number.POSITIVE_INFINITY },
  { label: "Under KES 1000", min: 0, max: 1000 },
  { label: "KES 1000 - 1500", min: 1000, max: 1500 },
  { label: "Over KES 1500", min: 1500, max: Number.POSITIVE_INFINITY },
]
